### ISSUE TITLE
Platinen Layout

### ISSUE THREAD

**Issue by Obelix411** [ronnythomas/Unterputz-Netzteil-Platine#2]
Guten Tag 
Kann man die Platinen bei ihnen erwerben bzw das Layout von ihnen bekommen ?

**Comment by ronnythomas** [comment]
> 
> 
> Guten Tag
> Kann man die Platinen bei ihnen erwerben bzw das Layout von ihnen bekommen ?

Bitte Per Mail pcb@kleine-aue.de
